"""empty message

Revision ID: 17a050db84a7
Revises: 
Create Date: 2020-05-27 02:10:33.706405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a050db84a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departement', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departement', 'region', ['region_id'], ['id'])
    op.add_column('ville', sa.Column('ID', sa.Integer(), nullable=False))
    op.drop_column('ville', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ville', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('ville', 'ID')
    op.drop_constraint(None, 'departement', type_='foreignkey')
    op.drop_column('departement', 'region_id')
    # ### end Alembic commands ###
